services:
  - type: web
    name: email-phishing-api
    env: python
    runtime: python-3.12.7
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install --no-cache-dir -r requirements.txt"
    startCommand: "python app/api.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: PIP_NO_CACHE_DIR
        value: "1"